/*
Invoice Ninja API Reference.

Testing MigrationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_MigrationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MigrationAPIService PostPurgeCompany", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var company string

		httpRes, err := apiClient.MigrationAPI.PostPurgeCompany(context.Background(), company).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MigrationAPIService PostPurgeCompanySaveSettings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var company string

		httpRes, err := apiClient.MigrationAPI.PostPurgeCompanySaveSettings(context.Background(), company).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MigrationAPIService PostStartMigration", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.MigrationAPI.PostStartMigration(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
